import { normalizeInventoryState } from "./normalize"
import type { InventoryState } from "./types"

export const ORG_NAME = "Plant IT"

export function createSeedInventory(): InventoryState {
  const seed = {
    laptops: [
      {
        id: "lap-1001",
        assetTag: "LT-1001",
        serialNumber: "5CG4120ABC",
        hostname: "ops-lt-01",
        make: "Dell",
        model: "Latitude 5550",
        laptopType: "standard",
        operatingSystem: "windows-11",
        department: "operations",
        assignedTo: "A. Rivera",
        location: "Plant 1 / Ops office",
        status: "in-service",
        purchaseDate: "2024-03-12",
        warrantyEnd: "2027-03-12",
        notes: "Shift supervisor unit",
      },
      {
        id: "lap-1002",
        serialNumber: "PF4A12XY",
        assetTag: "LT-1002",
        hostname: "eng-ws-04",
        make: "Lenovo",
        model: "ThinkPad P16",
        laptopType: "engineering",
        operatingSystem: "windows-11",
        department: "engineering",
        assignedTo: "J. Patel",
        location: "CAD room",
        status: "in-service",
        purchaseDate: "2023-11-02",
        warrantyEnd: "2026-11-02",
        notes: "32 GB / discrete GPU",
      },
      {
        id: "lap-1003",
        assetTag: "LT-1003",
        serialNumber: "",
        hostname: "mnt-rugged-02",
        make: "Panasonic",
        model: "Toughbook 55",
        laptopType: "field-rugged",
        operatingSystem: "windows-10",
        department: "maintenance",
        assignedTo: "K. Ng",
        location: "Maintenance shop",
        status: "in-service",
        purchaseDate: "2022-06-18",
        warrantyEnd: "2025-06-18",
        notes: "Serial missing from receiving paperwork",
      },
      {
        id: "lap-1004",
        assetTag: "LT-1004",
        serialNumber: "C02Y1ABC",
        hostname: "it-mac-01",
        make: "Apple",
        model: "MacBook Pro 14",
        laptopType: "standard",
        operatingSystem: "macos",
        department: "it",
        assignedTo: "M. Chen",
        location: "IT cage",
        status: "in-service",
        purchaseDate: "2025-01-20",
        warrantyEnd: "2028-01-20",
        notes: "",
      },
      {
        id: "lap-1005",
        assetTag: "LT-1005",
        serialNumber: "PF3Q88LM",
        hostname: "ot-eng-07",
        make: "Dell",
        model: "Precision 5680",
        laptopType: "engineering",
        operatingSystem: "windows-11",
        department: "ot-controls",
        assignedTo: "S. Alvarez",
        location: "Controls trailer",
        status: "in-service",
        purchaseDate: "2024-09-08",
        warrantyEnd: "2027-09-08",
        notes: "Studio 5000 + vendor VPN",
      },
      {
        id: "lap-1006",
        assetTag: "LT-1006",
        serialNumber: "5CD3344ZZ",
        hostname: "qa-lt-03",
        make: "HP",
        model: "EliteBook 860",
        laptopType: "standard",
        operatingSystem: "windows-11",
        department: "quality",
        assignedTo: "",
        location: "QA lab",
        status: "in-service",
        purchaseDate: "2023-04-01",
        warrantyEnd: "2026-04-01",
        notes: "Shared until backfill hire",
      },
      {
        id: "lap-1007",
        assetTag: "LT-1007",
        serialNumber: "R90XYZ11",
        hostname: "wh-kiosk-01",
        make: "Dell",
        model: "Latitude 5440",
        laptopType: "shared-kiosk",
        operatingSystem: "windows-11",
        department: "warehouse",
        assignedTo: "Receiving desk",
        location: "Dock office",
        status: "in-service",
        purchaseDate: "2024-07-15",
        warrantyEnd: "2027-07-15",
        notes: "Locked to receiving app",
      },
      {
        id: "lap-1008",
        assetTag: "LT-1008",
        serialNumber: "PF2LOAN3",
        hostname: "ctr-loan-12",
        make: "Lenovo",
        model: "ThinkPad L14",
        laptopType: "contractor-loaner",
        operatingSystem: "windows-11",
        department: "contractor",
        assignedTo: "Summit Electric",
        location: "IT cage / loaner shelf",
        status: "in-service",
        purchaseDate: "2023-02-11",
        warrantyEnd: "2026-02-11",
        notes: "Due back 2026-09-30",
      },
      {
        id: "lap-1009",
        assetTag: "LT-1009",
        serialNumber: "5CG9001QQ",
        hostname: "fin-lt-02",
        make: "Dell",
        model: "Latitude 5450",
        laptopType: "executive",
        operatingSystem: "windows-11",
        department: "finance",
        assignedTo: "R. Cole",
        location: "Admin building",
        status: "repair",
        purchaseDate: "2024-01-09",
        warrantyEnd: "2027-01-09",
        notes: "Keyboard replacement at depot",
      },
      {
        id: "lap-1010",
        assetTag: "LT-1010",
        serialNumber: "UBU-NX-19",
        hostname: "prd-hmi-spare",
        make: "Dell",
        model: "Latitude 5540",
        laptopType: "field-rugged",
        operatingSystem: "ubuntu",
        department: "production",
        assignedTo: "",
        location: "Line 3 cabinet",
        status: "spare",
        purchaseDate: "2021-08-22",
        warrantyEnd: "2024-08-22",
        notes: "Cold spare for HMI jump box",
      },
      {
        id: "lap-1011",
        assetTag: "LT-1011",
        serialNumber: "RHEL-EDGE-2",
        hostname: "ot-edge-02",
        make: "OnLogic",
        model: "Helix 511",
        laptopType: "field-rugged",
        operatingSystem: "rhel",
        department: "ot-controls",
        assignedTo: "Edge cluster",
        location: "MCC room",
        status: "in-service",
        purchaseDate: "2025-04-03",
        warrantyEnd: "2028-04-03",
        notes: "Historian collector",
      },
      {
        id: "lap-1012",
        assetTag: "LT-1012",
        serialNumber: "HR-MBP-08",
        hostname: "hr-lt-08",
        make: "HP",
        model: "EliteBook 840",
        laptopType: "standard",
        operatingSystem: "windows-11",
        department: "hr",
        assignedTo: "L. Brooks",
        location: "Admin / HR",
        status: "in-service",
        purchaseDate: "2024-05-21",
        warrantyEnd: "2027-05-21",
        notes: "",
      },
    ],
    printers: [
      {
        id: "prt-2001",
        assetTag: "PR-2001",
        serialNumber: "CNB1A2B3",
        make: "HP",
        model: "LaserJet M428fdw",
        printerType: "mfp",
        department: "quality",
        location: "QA lab",
        ipAddress: "10.20.8.41",
        status: "in-service",
        notes: "Scan to QA share",
      },
      {
        id: "prt-2002",
        assetTag: "PR-2002",
        serialNumber: "ZTC99812",
        make: "Zebra",
        model: "ZT411",
        printerType: "label",
        department: "warehouse",
        location: "Dock 2",
        ipAddress: "10.20.12.18",
        status: "in-service",
        notes: "4x6 shipping labels",
      },
      {
        id: "prt-2003",
        assetTag: "PR-2003",
        serialNumber: "EPL77410",
        make: "Epson",
        model: "WorkForce Pro WF-C5890",
        printerType: "inkjet",
        department: "engineering",
        location: "CAD room",
        ipAddress: "10.20.6.22",
        status: "in-service",
        notes: "Tabloid drawings",
      },
      {
        id: "prt-2004",
        assetTag: "PR-2004",
        serialNumber: "HP-PLT-01",
        make: "HP",
        model: "DesignJet T850",
        printerType: "plotter",
        department: "engineering",
        location: "Print room",
        ipAddress: "10.20.6.30",
        status: "repair",
        notes: "Cutter jam, parts on order",
      },
      {
        id: "prt-2005",
        assetTag: "PR-2005",
        serialNumber: "BRO-L8900",
        make: "Brother",
        model: "HL-L8900CDW",
        printerType: "laser",
        department: "it",
        location: "IT cage",
        ipAddress: "10.20.2.15",
        status: "spare",
        notes: "Hot spare",
      },
      {
        id: "prt-2006",
        assetTag: "PR-2006",
        serialNumber: "RIC-C3500",
        make: "Ricoh",
        model: "IM C3500",
        printerType: "mfp",
        department: "finance",
        location: "Admin copy room",
        ipAddress: "10.20.4.10",
        status: "in-service",
        notes: "Secure print",
      },
    ],
    software: [
      {
        id: "sw-3001",
        name: "AutoCAD",
        vendor: "Autodesk",
        entitlementId: "ADS-9981",
        licenseType: "per-seat",
        seatsPurchased: 8,
        seatsAssigned: 6,
        department: "engineering",
        renewalDate: "2026-11-01",
        annualCost: 12600,
        notes: "Network license server ENG-LIC-01",
      },
      {
        id: "sw-3002",
        name: "Studio 5000",
        vendor: "Rockwell",
        entitlementId: "RA-5500-22",
        licenseType: "per-seat",
        seatsPurchased: 4,
        seatsAssigned: 4,
        department: "ot-controls",
        renewalDate: "2026-09-10",
        annualCost: 18400,
        notes: "Includes FactoryTalk",
      },
      {
        id: "sw-3003",
        name: "Microsoft 365 E3",
        vendor: "Microsoft",
        entitlementId: "M365-PLANT",
        licenseType: "subscription",
        seatsPurchased: 120,
        seatsAssigned: 108,
        department: "it",
        renewalDate: "2027-01-15",
        annualCost: 43200,
        notes: "Enterprise agreement",
      },
      {
        id: "sw-3004",
        name: "PI Historian",
        vendor: "AVEVA",
        entitlementId: "PI-SRV-04",
        licenseType: "site",
        seatsPurchased: 1,
        seatsAssigned: 1,
        department: "ot-controls",
        renewalDate: "2026-12-01",
        annualCost: 28000,
        notes: "Plant 1 site license",
      },
      {
        id: "sw-3005",
        name: "Minitab",
        vendor: "Minitab",
        entitlementId: "MTB-QA-9",
        licenseType: "per-seat",
        seatsPurchased: 6,
        seatsAssigned: 6,
        department: "quality",
        renewalDate: "2026-08-30",
        annualCost: 5400,
        notes: "",
      },
      {
        id: "sw-3006",
        name: "CrowdStrike Falcon",
        vendor: "CrowdStrike",
        entitlementId: "CS-EDR-1",
        licenseType: "subscription",
        seatsPurchased: 140,
        seatsAssigned: 133,
        department: "it",
        renewalDate: "2027-03-01",
        annualCost: 21000,
        notes: "EDR on all Windows endpoints",
      },
    ],
    destructions: [
      {
        id: "dst-4001",
        assetKind: "laptop",
        assetId: "",
        assetTag: "LT-0090",
        serialNumber: "5CG2011OLD",
        department: "it",
        method: "secure-wipe-recycle",
        destroyedOn: "2026-05-14",
        witnessedBy: "M. Chen",
        certificateId: "COC-2026-014",
        reason: "End of life / Windows 10 cutoff",
        notes: "NIST 800-88 wipe, then recycler pickup",
      },
      {
        id: "dst-4002",
        assetKind: "printer",
        assetId: "",
        assetTag: "PR-0088",
        serialNumber: "HP-OLD-88",
        department: "warehouse",
        method: "physical-shred",
        destroyedOn: "2026-06-03",
        witnessedBy: "A. Rivera",
        certificateId: "COC-2026-019",
        reason: "Failed fuser, no parts",
        notes: "Hard drive pulled and shredded",
      },
      {
        id: "dst-4003",
        assetKind: "laptop",
        assetId: "",
        assetTag: "LT-0071",
        serialNumber: "PF1GONE",
        department: "contractor",
        method: "return-to-vendor",
        destroyedOn: "2026-07-22",
        witnessedBy: "",
        certificateId: "",
        reason: "Lease return",
        notes: "Need witness sign-off from leasing vendor",
      },
    ],
    history: [],
  }

  const normalized = normalizeInventoryState(
    seed as Parameters<typeof normalizeInventoryState>[0],
  )
  const first = normalized.laptops[0]
  if (!first) {
    return normalized
  }

  return {
    ...normalized,
    history: [
      {
        id: "hist-seed-1",
        at: "2024-03-12T12:00:00.000Z",
        action: "created",
        register: "laptop",
        recordId: first.id,
        inventoryNumber: first.inventoryNumber,
        assetTag: first.assetTag,
        serialNumber: first.serialNumber,
        summary: `Laptop ${first.inventoryNumber} angelegt (${first.assetTag})`,
        changes: [],
      },
      {
        id: "hist-seed-2",
        at: "2025-01-08T15:30:00.000Z",
        action: "updated",
        register: "laptop",
        recordId: first.id,
        inventoryNumber: first.inventoryNumber,
        assetTag: first.assetTag,
        serialNumber: first.serialNumber,
        summary: `Laptop ${first.inventoryNumber}: assignedTo, location geändert`,
        changes: [
          { field: "assignedTo", from: "", to: first.assignedTo },
          { field: "location", from: "Receiving", to: first.location },
        ],
      },
    ],
  }
}
