import type { TableName } from "@/lib/types"

const COLUMN_LABEL: Record<string, string> = {
  sku: "Artikel",
  name: "Name",
  shift: "Schicht",
  plant: "Werk",
  line: "Linie",
  station: "Station",
  machine: "Maschine",
  units: "Stück",
  good_units: "Gutteile",
  scrap_units: "Ausschuss",
  rework_units: "Nacharbeit",
  over_takt_ms: "Über Soll ms",
  defects: "Fehler",
  target_cycle_ms: "Soll-Takt ms",
  up_plant: "Vor-Werk",
  up_line: "Vorlinie",
  down_plant: "Nach-Werk",
  down_line: "Nachlinie",
  upstream: "Zulauf",
  downstream: "Abnahme",
  upstream_downtime_min: "Stillstand vorne Min",
  downstream_starve_min: "Hunger hinten Min",
  fail_code: "Fehlercode",
  fail_reason: "Fehlergrund",
  hits: "Treffer",
  cycles: "Takte",
  fpy_pct: "Erstausbeute %",
  avg_cycle_ms: "Mittl. Takt ms",
  file_name: "Datei",
  source_share: "Freigabe",
  downtime: "Stillstand",
  alarms: "Alarme",
  servers: "Server",
  controllers: "Steuerungen",
  status: "Status",
  error_message: "Fehler",
  reason_code: "Ursache",
  reason_text: "Ursachentext",
  minutes: "Minuten",
  bucket: "Intervall",
  bucket_ms: "Intervall ms",
  file_id: "Datei-ID",
  cycle_id: "Takt-ID",
  event_id: "Ereignis-ID",
  alarm_id: "Alarm-ID",
  sample_id: "Proben-ID",
  shift_date: "Schichttag",
  ingested_at: "Geladen am",
  byte_size: "Bytes",
  cycle_count: "Takte",
  downtime_count: "Stillstände",
  alarm_count: "Alarme",
  server_sample_count: "Serverproben",
  controller_count: "Steuerungen",
  controller_id: "Steuerung",
  work_order: "Auftrag",
  serial: "Serie",
  operator_id: "Bediener",
  started_at: "Start",
  ended_at: "Ende",
  cycle_ms: "Takt ms",
  result: "Ergebnis",
  good_qty: "Gut",
  scrap_qty: "Ausschuss",
  rework_qty: "Nacharbeit",
  duration_ms: "Dauer ms",
  category: "Kategorie",
  raised_at: "Aufgetreten",
  cleared_at: "Quittiert am",
  severity: "Stufe",
  code: "Code",
  message: "Meldung",
  ack_state: "Quittierung",
  server_id: "Server",
  server_role: "Rolle",
  sampled_at: "Gemessen",
  cpu_pct: "CPU %",
  mem_pct: "RAM %",
  disk_pct: "Platte %",
  plc_scan_ms: "SPS-Scan ms",
  heartbeat_ms: "Taktimpuls ms",
  queue_depth: "Warteschlange",
  missed_heartbeats: "Verpasste Impulse",
  session_count: "Sitzungen",
  network_err: "Netzfehler",
  temperature_c: "Temperatur °C",
  vendor: "Hersteller",
  model: "Modell",
  firmware: "Firmware",
  ip_address: "IP",
  rack: "Baugruppenträger",
  slot: "Steckplatz",
  scan_ms_avg: "Scan mittel ms",
  scan_ms_p95: "Scan P95 ms",
  io_faults: "E/A-Fehler",
  last_fault_code: "Letzter Fehler",
  last_seen: "Zuletzt gesehen",
  run_mode: "Betriebsart",
  hour: "Stunde",
  n: "Anzahl",
  events: "Ereignisse",
  open_alarms: "Offene Alarme",
  downtime_min: "Stillstand Min",
  downtime_ms: "Stillstand ms",
  starve_ms: "Hunger ms",
  window_ms: "Fenster ms",
  unplanned_ms: "Ungeplant ms",
  ideal_ms: "Ideal ms",
  cumulative_pct: "Kumuliert %",
}

const TABLE_LABEL: Record<TableName, string> = {
  ingest_files: "Dateien",
  cycles: "Takte",
  downtime: "Stillstand",
  alarms: "Alarme",
  server_samples: "Serverproben",
  controllers: "Steuerungen",
}

const VALUE_LABEL: Record<string, string> = {
  PASS: "Gut",
  FAIL: "Ausschuss",
  REWORK: "Nacharbeit",
  INFO: "Hinweis",
  WARN: "Warnung",
  CRITICAL: "Kritisch",
  PLANNED: "Geplant",
  UNPLANNED: "Ungeplant",
  CHANGEOVER: "Rüsten",
  RUN: "Lauf",
  STOP: "Halt",
  FAULT: "Störung",
  OPEN: "Offen",
  ACKED: "Quittiert",
  CLEARED: "Gelöscht",
  ok: "in Ordnung",
  error: "Fehler",
  STARVE: "Hunger",
  "E-STOP": "Not-Halt",
  JAM: "Stau",
  TOOL: "Werkzeug",
  CO: "Rüsten",
}

export function columnLabel(column: string): string {
  return COLUMN_LABEL[column] ?? column
}

export function tableLabel(table: TableName): string {
  return TABLE_LABEL[table]
}

export function valueLabel(value: string): string {
  return VALUE_LABEL[value] ?? value
}
