const COLUMN_LABEL: Record<string, string> = {
  sku: "SKU",
  name: "Name",
  shift: "Schicht",
  plant: "Werk",
  line: "Linie",
  station: "Station",
  machine: "Maschine",
  units: "Stück",
  good_units: "Gutteile",
  scrap_units: "Ausschuss",
  list_price: "Listenpreis",
  material_cost: "Material",
  unit_cost: "Stückkosten",
  margin: "Marge",
  margin_pct: "Marge %",
  rate_per_hour: "Stundenlohn",
  up_plant: "Vor-Werk",
  up_line: "Vorlinie",
  down_plant: "Nach-Werk",
  down_line: "Nachlinie",
  upstream: "Zulauf",
  downstream: "Abnahme",
  upstream_downtime_min: "Stillstand vorne Min",
  downstream_starve_min: "Hunger hinten Min",
  fail_code: "Fehlercode",
  fail_reason: "Fehlergrund",
  hits: "Treffer",
  cycles: "Takte",
  fpy_pct: "FPY %",
  avg_cycle_ms: "Mittl. Takt ms",
  file_name: "Datei",
  source_share: "Freigabe",
  downtime: "Stillstand",
  alarms: "Alarme",
  servers: "Server",
  controllers: "Steuerungen",
  status: "Status",
  reason_code: "Ursache",
  minutes: "Minuten",
  bucket: "Bucket",
  bucket_ms: "Bucket ms",
}

export function columnLabel(column: string): string {
  return COLUMN_LABEL[column] ?? column
}
